[package]
name = "rust-toon-system-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
calamine.workspace = true
chrono.workspace = true
rust-toon-framework-common.workspace = true
rust-toon-framework-database.workspace = true
rust-toon-framework-redis.workspace = true
rust-toon-framework-security.workspace = true
rust-toon-framework-web.workspace = true
rust-toon-system-api.workspace = true
rust_xlsxwriter.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
