[package]
name = "rust-toon-infra-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
hex.workspace = true
hmac.workspace = true
rust-toon-framework-common.workspace = true
rust-toon-framework-database.workspace = true
rust-toon-framework-jobs.workspace = true
rust-toon-framework-resilience.workspace = true
rust-toon-framework-security.workspace = true
rust-toon-framework-telemetry.workspace = true
rust-toon-framework-web.workspace = true
rust-toon-infra-api.workspace = true
rust_xlsxwriter.workspace = true
redis.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
tower.workspace = true
